In [1]:
import numpy as np

## Difference in python list and numpy array

In [2]:
# In python
my_list = [1,2,3,4]
print(my_list*2)    # Result: [1,2,3,4,1,2,3,4,]

# It performs slow operations

# In numpy

array = np.array([1,2,3,4])
print(array*2)      # Result: [2,4,6,8]

# It performs fast operations

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


## Creation of numpy array

In [3]:
# A array can be of any dimensions

array_1d = np.array([1,2,3]) # Created 1 dimension array

array_2d = np.array(
    [[1,2,3,4,5],
    [6,7,8,9,10]]
) # Created 2 dimension array

array_3d = np.array(
    [[[1,2,3],
    [4,5,6],
    [0,0,0]]]
) # Created 3 dimension array

# We can find the dimension by .ndim

print(array_1d.ndim)
print(array_2d.ndim)
print(array_3d.ndim)

1
2
3


## Important attributes/Properties of numpy

##### .ndim: gives the dimension of an array

In [ ]:
dimension1 = np.array([1,2,3])
dimension2 = np.array([[1,2,3]])

print(dimension1.ndim,
      dimension2.ndim)


1 2
(2, 3)
(2, 3, 3) 3


##### .shape: It returns the dimensions of the array as a tuple

In [10]:
shape1 = np.array([[1,2,3],
                   [4,5,6]])
print(shape1.shape)

# Result: (2,3) = 2rows, 3column

shape2 = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print(shape2.shape)

# Result: (2,3,3) = 2 matrices of 3 rows 3 column

(2, 3)
(2, 3, 3)


##### .size: gives the total elements of the array

In [14]:
size1 = np.array([1,2,3])
size2 = np.array([[1,2,3],[4,5,6]])
size3 = np.array([[[1,2,3],[0,0,0],[9,9,9]]])

print(size1.size)
print(size2.size)
print(size3.size)

3
6
9


##### .dtype gives the data type of the array

In [ ]:
type1 = np.array([1,2,3])
type2 = np.array([1.0,2.3,3.2])

print(type1.dtype)
print(type2.dtype)

int64 24
float64 24


##### .T teanspose of array

In [21]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


## Indexing and Slicing

In [ ]:
# Indexing -------------------->

array_word = np.array(
    [
        [['A','B','C'],['D','E','F'],['G','H','I']],
        [['J','K','L'],['M','N','O'],['P','Q','R']],
        [['S','T','U'],['V','W','X'],['Y','Z',' ']],
    ]
)

word = array_word[2,2,0] + array_word[1,1,2] + array_word[2,0,2] + array_word[1,2,2] + array_word[2,2,2] + array_word[0,0,0] + array_word[2,0,0] + array_word[2,0,0]
print(word)

# Slicing ---------------------->

array_slicing = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16],
    ]
)

# array[start:end:step]
print(array_slicing[1:3])     # Slice the rows
print(array_slicing[1][1:3])     # Slice the digit of a specific row
print(array_slicing[:,2])       # Slice to get column by all row

d3_array = np.array(
    [
        [
            [0,1,2],
            [3,4,5],
            [6,7,8],
            [0,9,7],
            [1,5,6]
        ]
    ]
)

# arr[block, row(optional select all in default), start:end]
print(d3_array[0, 1:3])

YOUR ASS
[[ 5  6  7  8]
 [ 9 10 11 12]]
[6 7]
[ 3  7 11 15]
[]


### Vectorized math funcs

In [39]:
array_vec = np.array([1,2,3])

print(np.sqrt(array_vec))
print(np.pi)

radii = np.array([1,2,3])

print(np.pi * radii **2)

[1.         1.41421356 1.73205081]
3.141592653589793
[ 3.14159265 12.56637061 28.27433388]


### Scalar arthmetic operation

In [40]:
array_arth = np.array([1,2,3])
print(array_arth + 1)
print(array_arth - 2)
print(array_arth * 2)
print(array_arth / 2)
print(array_arth // 2)
print(array_arth ** 2)
print(array_arth > 2)

[2 3 4]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[0 1 1]
[1 4 9]
[False False  True]


### Element-wise arthmetic operation

In [38]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])

print(array_1 + array_2)
print(array_1 - array_2)
print(array_1 * array_2)
print(array_1 / array_2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


###  Comparison operators

In [37]:
scores = np.array([91, 55, 100, 73, 82, 64])

scores[scores<60] = 0
print(scores)

[ 91   0 100  73  82  64]


## Broadcasting

In [41]:
array1_broad = np.array(
    [
        [1,2,3,4]
    ]
)
array2_broad = np.array(
    [
        [1],[2],[3],[4]
    ]
)

print(array1_broad.shape)
print(array2_broad.shape)

broad = array1_broad * array2_broad
print(broad,broad.shape,broad.ndim)

array_1_broad = np.array(
    [
        [1,2,3,4,5,6,7,8,9,10]
    ]
)
array_2_broad = np.array(
    [
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9],
        [10]
    ]
)

print(array_1_broad.shape,array_1_broad.ndim)
print(array_2_broad.shape,array_2_broad.ndim)

broad2 = array_1_broad * array_2_broad

print(broad2, broad2.shape, broad2.ndim)

# NOTE: Dimension doesn't change and only the size increase

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]] (4, 4) 2
(1, 10) 2
(10, 1) 2
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] (10, 10) 2


## aggregrate function

In [42]:
array_stat = np.array(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ]
)

print("Sum: ",np.sum(array_stat))    
print("Mean: ",np.mean(array_stat))  
print("standard deviation: ",np.std(array_stat)) 
print("Variance: ",np.var(array_stat)) 
print("min value: ",np.min(array_stat))    
print("max value: ",np.max(array_stat))    
print("postion of min value: ",np.argmin(array_stat)) 
print("postion of max value: ",np.argmax(array_stat)) 

print("Sum at a column: ",np.sum(array_stat, axis = 0))   
print("Sum at a row: ",np.sum(array_stat, axis = 1))


Sum:  55
Mean:  5.5
standard deviation:  2.8722813232690143
Variance:  8.25
min value:  1
max value:  10
postion of min value:  0
postion of max value:  9
Sum at a column:  [ 7  9 11 13 15]
Sum at a row:  [15 40]



### Filtering = Refers to the process of selecting elements from an array that match a given condition

In [ ]:
ages = np.array(
    [
        [21, 17, 19, 20, 16, 30, 18, 65],
        [39, 22, 15, 99, 18, 19, 20, 21]
    ]
)

# booling indexing used which flattens the shape
teenagers = ages[ages<18]
print(teenagers)

# adults = ages[(ages>=18) & (ages<65)]
# adults = ages[(ages>=18) | (ages<65)]
# print(adults)

seniors = ages[ages>=65]
print(seniors)

evens = ages[ages % 2 == 0]
print(evens)

# by using where function it preserve the shape
adults = np.where(ages>=18, ages, np.nan)
print(adults)

rng = np.random.default_rng() # seed = 1 hepls to make same results
print(rng.integers(low = 1,high = 7, size=(1,2)))

print(np.random.uniform(low=-1,high=1, size=(3,4)))

rng_array = np.array([1,2,3,4,5])
rng.shuffle(rng_array)
print(rng_array)

fruits = np.array(["🍎","🍊","🍌","🥥","🍍"])
fruits = rng.choice(fruits, size = (3,3))
print(fruits)